#!/bin/bash
export DISPLAY=$(w -h | awk "{print \$3}" | grep -E "^:[0-9]+" | head -n 1)
if [ -z "$DISPLAY" ]; then
    export DISPLAY=:10.0
fi
export XAUTHORITY=/root/.Xauthority
echo "Using DISPLAY=$DISPLAY"
curl -s -o /dev/null "https://www.baidu.com" # Dummy traffic
NODE_ENV=production /usr/local/bin/openclaw gateway
